"""Credential provisioning: the remediation behind check family A.

The rule this module exists to enforce is that **a credential value never
reaches disk**. Quickstarts universally instruct the reader to paste a live key
into `.env`, and that file then outlives the tutorial, gets copied between
machines, and eventually gets committed. Storing the value in the OS keychain
and leaving only its *name* in the project removes the artifact entirely.

Named ``credentials`` rather than ``secrets`` deliberately: a module named
``secrets`` inside this package invites confusion with the standard library
module of that name, and confusion in the module that handles keys is expensive.

Failure is loud by design. When no keychain backend exists - a headless CI box,
typically - :class:`KeyringStore` refuses rather than silently falling back to a
file. A security tool that quietly degrades to the insecure path is worse than
one that stops, because the user believes they are protected.
"""

from __future__ import annotations

import re
from typing import Final, Protocol

from toolseal.errors import ConfigError

SERVICE_NAME: Final = "toolseal"

# Backends that exist only to raise when used. `keyring` selects one of these
# when the platform offers no real credential store.
NULL_BACKENDS: Final[frozenset[str]] = frozenset({"keyring.backends.fail.Keyring"})

# Lines a project needs so that credential-bearing files cannot be committed.
# Order is stable so a regenerated .gitignore diffs empty.
GITIGNORE_ENTRIES: Final[tuple[str, ...]] = (
    ".env",
    ".env.*",
    "!.env.example",
    "*.pem",
    "*.key",
    "credentials.json",
)

GITIGNORE_HEADER: Final = "# Credential files - added by toolseal (checks A1, A2)"

# Minimal hook set for a generated project. detect-private-key is the one that
# matters here; the rest keep the hook file from being the only thing running.
PRECOMMIT_CONFIG: Final = """\
# Generated by toolseal. `pre-commit install` activates these.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key   # A2: refuse a commit carrying key material
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
"""

# Values that look like a placeholder rather than a real credential. Storing one
# of these means the user pasted the example, and they will get a confusing
# authentication error much later if it is accepted here.
_PLACEHOLDER = re.compile(
    r"^\s*(|<.*>|your[-_ ]?(api[-_ ]?)?key.*|xxx+|change[-_ ]?me|todo|\.\.\.)\s*$",
    re.IGNORECASE,
)


class CredentialStore(Protocol):
    """Somewhere a credential can live that is not the project directory."""

    @property
    def name(self) -> str: ...

    def available(self) -> bool:
        """Whether this store can actually be used on this machine."""
        ...

    def set(self, account: str, value: str) -> None: ...

    def get(self, account: str) -> str | None: ...

    def delete(self, account: str) -> None: ...


class KeyringStore:
    """The OS keychain, via ``keyring``.

    Windows Credential Manager, macOS Keychain, or Secret Service on Linux.
    ``keyring`` selects the backend; this class only decides whether the one it
    selected is real.
    """

    name: Final = "os-keychain"

    def __init__(self, service: str = SERVICE_NAME) -> None:
        self._service = service

    def available(self) -> bool:
        """True when a usable backend is present.

        ``keyring`` installs a null backend when nothing real is found, and that
        backend raises on use rather than reporting itself as absent, so the
        check has to inspect what was selected.

        Identified by qualified name rather than ``isinstance``. Importing the
        null backend's class here would be a second import of ``keyring``, and
        the two could resolve differently - which is exactly the bug that made
        an available keychain report itself as missing.
        """
        try:
            import keyring
        except ImportError:
            return False

        backend = keyring.get_keyring()
        qualified = f"{type(backend).__module__}.{type(backend).__qualname__}"
        if qualified in NULL_BACKENDS:
            return False

        # A chainer with nothing in it behaves like the null backend.
        children = getattr(backend, "backends", None)
        return not (children is not None and not list(children))

    def _require_backend(self) -> None:
        if not self.available():
            message = (
                "no OS keychain is available on this machine, so the credential "
                "cannot be stored securely. Set the value in the environment "
                "instead of having toolseal write it to a file."
            )
            raise ConfigError(message)

    def set(self, account: str, value: str) -> None:
        """Store *value*. Rejects placeholders and blanks before they are saved."""
        self._require_backend()
        if is_placeholder(value):
            message = (
                f"the value given for {account!r} looks like a placeholder rather than "
                "a credential; nothing was stored"
            )
            raise ConfigError(message)

        import keyring

        try:
            keyring.set_password(self._service, account, value)
        except Exception as exc:
            # Deliberately does not include the exception's text: some backends
            # echo the value they were handed.
            message = f"the OS keychain refused to store {account!r} ({type(exc).__name__})"
            raise ConfigError(message) from None

    def get(self, account: str) -> str | None:
        self._require_backend()
        import keyring

        try:
            return keyring.get_password(self._service, account)
        except Exception as exc:
            message = f"the OS keychain refused to read {account!r} ({type(exc).__name__})"
            raise ConfigError(message) from None

    def delete(self, account: str) -> None:
        self._require_backend()
        import keyring

        try:
            keyring.delete_password(self._service, account)
        except Exception:
            # Deleting something already absent is the desired end state.
            return


def is_placeholder(value: str) -> bool:
    """Whether *value* is an example rather than a credential."""
    return _PLACEHOLDER.match(value) is not None


def merge_gitignore(existing: str) -> str:
    """Add the credential ignore rules to *existing*, idempotently.

    Rewriting the file wholesale would discard a user's own rules, and appending
    unconditionally would grow a duplicate block on every run. Only genuinely
    missing lines are added.
    """
    present = {line.strip() for line in existing.splitlines()}
    missing = [entry for entry in GITIGNORE_ENTRIES if entry not in present]
    if not missing:
        return existing

    prefix = existing if existing.endswith("\n") or not existing else existing + "\n"
    block = "\n".join([GITIGNORE_HEADER, *missing])
    separator = "\n" if prefix else ""
    return f"{prefix}{separator}{block}\n"


def environment_reference(env_var: str) -> str:
    """The `.env.example` line for *env_var*: a name, never a value."""
    return f"{env_var}="
