"""Combines Study 1's four strata into one `RESULTS.md`.

`llm-generated` already ran, via `bench/generated.py` against a local Ollama
model, and its output lives at `research/studies/s1/results.json` - left
exactly where it was, in its own shape, because `bench/coverage.py`'s Study 5
re-cut (`recut_study1_by_control`) reads that exact path expecting that exact
shape. This module reads it as committed and never re-derives it - the
protocol's "generated by the committed harness" rule is satisfied by the
original run, and re-running a live model here would draw a fresh sample
rather than reproduce the recorded one, which is not what "extend, do not
replace" asks for.

The three network-collected strata are read from their flat
`results.<stratum>.json` siblings (`bench.corpus.write_flat_index`) - the
same files `OTHER_S1_STRATA` checks for - so this module and Study 5's re-cut
agree on where a stratum's result lives without either importing the other.

Only `RESULTS.md` is written here. There is deliberately no combined
`results.json`: `research/studies/s1/results.json` must keep meaning
"the llm-generated stratum's own result" for `bench/coverage.py`, and a
second file with a different, nested shape under the same name one directory
over would invite exactly the confusion this avoids.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Final

from bench import corpus
from bench.generated import to_markdown as llm_generated_markdown

INTRO: Final = """# Study 1 - Posture of ecosystem setup guidance

RQ1: does the ecosystem's own setup guidance produce insecure configurations?
Four strata, sampled and reported separately, per
[`../../evaluation-protocol.md`](../../evaluation-protocol.md#study-1--posture-of-ecosystem-setup-guidance-rq1).
Selection criteria for `official-docs`, `mcp-servers` and `templates` are
fixed in [`selection-criteria.md`](selection-criteria.md), committed before
any of the three was collected. What this project does with a finding
against a third-party artefact - and the absolute rule that a live credential
never appears here - is fixed in
[`../../../DISCLOSURE.md`](../../../DISCLOSURE.md).

Per-stratum figures are reported first, because an aggregate can hide a
stratum the others do not resemble; the combined table at the end is a
summary of them, not a replacement for them.
"""

STRATA: Final = (
    ("official_docs", "official-docs"),
    ("mcp_servers", "mcp-servers"),
    ("templates", "templates"),
    ("llm_generated", "llm-generated"),
)


def combine(
    official_docs_payload: dict[str, Any],
    mcp_servers_payload: dict[str, Any],
    templates_payload: dict[str, Any],
    llm_generated_payload: dict[str, Any],
) -> dict[str, Any]:
    return {
        "official_docs": official_docs_payload,
        "mcp_servers": mcp_servers_payload,
        "templates": templates_payload,
        "llm_generated": llm_generated_payload,
    }


def _llm_generated_section(payload: dict[str, Any]) -> str:
    text = llm_generated_markdown(payload)
    lines = text.splitlines()
    if lines and lines[0].startswith("# "):
        lines[0] = "## Stratum: `llm-generated`"
    return "\n".join(lines) + "\n"


def _aggregate_row(label: str, aggregate: dict[str, Any]) -> str:
    considered = aggregate.get("candidates_considered", aggregate.get("completions_total"))
    mean_score = aggregate["mean_score"]
    return (
        f"| `{label}` | {considered} | {aggregate['materialised']} | "
        f"{aggregate['excluded']} | {mean_score} | {aggregate['with_critical_finding']} |"
    )


def _aggregate_section(combined: dict[str, Any]) -> str:
    rows = [_aggregate_row(label, combined[key]["aggregate"]) for key, label in STRATA]
    return "\n".join(
        [
            "## Aggregate across strata",
            "",
            "Official documentation and a random template repository are "
            "different populations; this table summarises the sections above, "
            "it does not substitute for reading them.",
            "",
            "| stratum | considered | materialised | excluded | mean score | critical |",
            "| --- | ---: | ---: | ---: | ---: | ---: |",
            *rows,
            "",
        ]
    )


def render_markdown(combined: dict[str, Any]) -> str:
    sections = [
        INTRO,
        corpus.to_markdown(combined["official_docs"]),
        corpus.to_markdown(combined["mcp_servers"]),
        corpus.to_markdown(combined["templates"]),
        _llm_generated_section(combined["llm_generated"]),
        _aggregate_section(combined),
    ]
    return "\n".join(sections)


def _read(path: Path) -> dict[str, Any]:
    payload: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    return payload


def write(s1_root: Path) -> dict[str, Any]:
    """Read every stratum's committed result and write the combined `RESULTS.md`."""
    combined = combine(
        _read(s1_root / "results.official-docs.json"),
        _read(s1_root / "results.mcp-servers.json"),
        _read(s1_root / "results.templates.json"),
        _read(s1_root / "results.json"),
    )
    (s1_root / "RESULTS.md").write_text(render_markdown(combined), encoding="utf-8")
    return combined
